services:
  # 🗄️ MariaDB
  db:
    image: mariadb:11
    container_name: db
    restart: always
    ports:
      - "${DB_HOST_PORT}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -u root -p$${MARIADB_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 20

  # ⚙️ Backend Spring Boot
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: tpcomplet-backend
    container_name: backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${BACK_HOST_PORT}:8081"

  # 🌐 Frontend React
  frontend:
    build:
      context: ./src/main/webapp/reactjs
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: /api
    image: tpcomplet-frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "${FRONT_HOST_PORT}:80"

  # 📈 Prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    depends_on:
      - backend
    ports:
      - "${PROM_HOST_PORT}:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  # 📊 Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    ports:
      - "${GRAFANA_HOST_PORT}:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  db_data:
  grafana_data:
